<a href="https://colab.research.google.com/github/alfianrifqy/STKI/blob/preprocessing-nltk/Clean_Dataset_Stem.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
dataset = pd.read_csv('clean_dataset.csv', sep=';')

In [3]:
dataset.head()

,Unnamed: 0,Sentiment,Instagram Comment Text,step01,tokens,final_tokens,step02
0,0,0,<USERNAME> TOLOL!! Gak ada hubungan nya kegug...,username tolol gak ada hubungan nya keguguran ...,"['username', 'tolol', 'gak', 'ada', 'hubungan'...","['username', 'tolol', 'gak', 'ada', 'hubungan'...",username tolol gak ada hubungan nya keguguran ...
1,1,0,Geblek lo tata...cowo bgt dibela2in balikan......,geblek lo tata cowo bgt dibelain balikan hadew...,"['geblek', 'lo', 'tata', 'cowo', 'bgt', 'dibel...","['geblek', 'lo', 'tata', 'cowo', 'bgt', 'dibel...",geblek lo tata cowo bgt dibelain balikan hadew...
2,2,0,Kmrn termewek2 skr lengket lg duhhh kok labil ...,kmrn termewek skr lengket lg duhhh kok labil b...,"['kmrn', 'termewek', 'skr', 'lengket', 'lg', '...","['kmrn', 'termewek', 'skr', 'lengket', 'lg', '...",kmrn termewek skr lengket lg duhhh kok labil b...
3,3,0,"Intinya kalau kesel dengan ATT nya, gausah ke ...",intinya kalau kesel dengan att nya gausah ke a...,"['intinya', 'kalau', 'kesel', 'dengan', 'att',...","['intinya', 'kalau', 'kesel', 'dengan', 'att',...",intinya kalau kesel dengan att nya gausah ke a...
4,4,0,"hadewwwww permpuan itu lg!!!!sakit jiwa,knp ha...",hadewwwww permpuan itu lg sakit jiwa knp harus...,"['hadewwwww', 'permpuan', 'itu', 'lg', 'sakit'...","['hadewwwww', 'permpuan', 'itu', 'lg', 'sakit'...",hadewwwww permpuan itu lg sakit jiwa knp harus...

In [5]:
!pip install Sastrawi

Collecting Sastrawi
  Downloading Sastrawi-1.0.1-py2.py3-none-any.whl.metadata (909 bytes)
Downloading Sastrawi-1.0.1-py2.py3-none-any.whl (209 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 209.7/209.7 kB 8.2 MB/s eta 0:00:00
Installing collected packages: Sastrawi
Successfully installed Sastrawi-1.0.1

In [6]:
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory
factory = StemmerFactory()
stemmer = factory.create_stemmer()

In [7]:
from Sastrawi.StopWordRemover.StopWordRemoverFactory import StopWordRemoverFactory, StopWordRemover, ArrayDictionary

factory = StopWordRemoverFactory()

more_stopword = ['sih', 'nya','rt','loh','lah', 'dd', 'mah', 'nye', 'eh', 'ehh', 'ah', 'yang','yg']

# Tambahkan Stopword Baru
data = factory.get_stop_words()+more_stopword

stopwords_sastrawi = factory.create_stop_word_remover()

dictionary = ArrayDictionary(data)
str_stopwords = StopWordRemover(dictionary)

In [8]:
dataset['finalText_str'] = dataset['step02'].apply(str)

In [10]:
i=0
final_string = []
s = ""
for sentence in dataset["finalText_str"].values:
    filteredSentence = []
    EachReviewText = ""
    st = str_stopwords.remove(sentence)
    s = (stemmer.stem(st))
    filteredSentence.append(s)

    EachReviewText = ' '.join(filteredSentence)
    final_string.append(EachReviewText)

In [12]:
dataset.loc[:, ('ProcessedText')] = final_string

In [13]:
dataset

,Unnamed: 0,Sentiment,Instagram Comment Text,step01,tokens,final_tokens,step02,finalText_str,ProcessedText
0,0,0,<USERNAME> TOLOL!! Gak ada hubungan nya kegug...,username tolol gak ada hubungan nya keguguran ...,"['username', 'tolol', 'gak', 'ada', 'hubungan'...","['username', 'tolol', 'gak', 'ada', 'hubungan'...",username tolol gak ada hubungan nya keguguran ...,username tolol gak ada hubungan nya keguguran ...,username tolol gak hubung gugur dgn pake hijab...
1,1,0,Geblek lo tata...cowo bgt dibela2in balikan......,geblek lo tata cowo bgt dibelain balikan hadew...,"['geblek', 'lo', 'tata', 'cowo', 'bgt', 'dibel...","['geblek', 'lo', 'tata', 'cowo', 'bgt', 'dibel...",geblek lo tata cowo bgt dibelain balikan hadew...,geblek lo tata cowo bgt dibelain balikan hadew...,geblek lo tata cowo bgt bain balik hadeww ntar...
2,2,0,Kmrn termewek2 skr lengket lg duhhh kok labil ...,kmrn termewek skr lengket lg duhhh kok labil b...,"['kmrn', 'termewek', 'skr', 'lengket', 'lg', '...","['kmrn', 'termewek', 'skr', 'lengket', 'lg', '...",kmrn termewek skr lengket lg duhhh kok labil b...,kmrn termewek skr lengket lg duhhh kok labil b...,kmrn mewek skr lengket lg duhhh kok labil bgt ...
3,3,0,"Intinya kalau kesel dengan ATT nya, gausah ke ...",intinya kalau kesel dengan att nya gausah ke a...,"['intinya', 'kalau', 'kesel', 'dengan', 'att',...","['intinya', 'kalau', 'kesel', 'dengan', 'att',...",intinya kalau kesel dengan att nya gausah ke a...,intinya kalau kesel dengan att nya gausah ke a...,inti kalau kesel att gausah anak kasi buat kem...
4,4,0,"hadewwwww permpuan itu lg!!!!sakit jiwa,knp ha...",hadewwwww permpuan itu lg sakit jiwa knp harus...,"['hadewwwww', 'permpuan', 'itu', 'lg', 'sakit'...","['hadewwwww', 'permpuan', 'itu', 'lg', 'sakit'...",hadewwwww permpuan itu lg sakit jiwa knp harus...,hadewwwww permpuan itu lg sakit jiwa knp harus...,hadewwwww permpuan lg sakit jiwa knp dia jd pe...
...,...,...,...,...,...,...,...,...,...
395,395,1,Bangga sama suami yg selalu ingat istri disela...,bangga sama suami yg selalu ingat istri disela...,"['bangga', 'sama', 'suami', 'yg', 'selalu', 'i...","['bangga', 'sama', 'suami', 'yg', 'selalu', 'i...",bangga sama suami yg selalu ingat istri disela...,bangga sama suami yg selalu ingat istri disela...,bangga sama suami selalu ingat istri sela wakt...
396,396,1,Apaoun pekerjaannya yg penting halal u tuk men...,apaoun pekerjaannya yg penting halal tuk menaf...,"['apaoun', 'pekerjaannya', 'yg', 'penting', 'h...","['apaoun', 'pekerjaannya', 'yg', 'penting', 'h...",apaoun pekerjaannya yg penting halal tuk menaf...,apaoun pekerjaannya yg penting halal tuk menaf...,apaoun kerja penting halal tuk nafkah keluarga...
397,397,1,Gojek itu mayoritas pegangguran yang lama gak ...,gojek itu mayoritas pegangguran yang lama gak ...,"['gojek', 'itu', 'mayoritas', 'pegangguran', '...","['gojek', 'itu', 'mayoritas', 'pegangguran', '...",gojek itu mayoritas pegangguran yang lama gak ...,gojek itu mayoritas pegangguran yang lama gak ...,gojek mayoritas pegangguran lama gak kerja tru...
398,398,1,<USERNAME> aslinya cantik dan ayu loh mbak kr...,username aslinya cantik dan ayu loh mbak krn a...,"['username', 'aslinya', 'cantik', 'dan', 'ayu'...","['username', 'aslinya', 'cantik', 'dan', 'ayu'...",username aslinya cantik dan ayu loh mbak krn a...,username aslinya cantik dan ayu loh mbak krn a...,username asli cantik ayu mbak krn aku temu lan...
399,399,1,"<USERNAME> suami saya seumuran sama saya mba,...",username suami saya seumuran sama saya mba mal...,"['username', 'suami', 'saya', 'seumuran', 'sam...","['username', 'suami', 'saya', 'seumuran', 'sam...",username suami saya seumuran sama saya mba mal...,username suami saya seumuran sama saya mba mal...,username suami umur sama mba malah tua beberap...

In [14]:
dataset.to_csv('clean_dataset_stem.csv',sep=';')